# Generated by Django 5.2.5 on 2025-12-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_carritotemporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Altura en centímetros', max_digits=10),
        ),
        migrations.AddField(
            model_name='idea',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ancho en centímetros', max_digits=10),
        ),
    ]
