# Generated by Django 5.2.5 on 2025-12-13 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_idea_altura_idea_ancho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pago',
            name='nombre_completo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('email_cliente', models.EmailField(blank=True, max_length=100)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20)),
                ('direccion_cliente', models.CharField(blank=True, max_length=300)),
                ('ciudad_cliente', models.CharField(blank=True, max_length=100)),
                ('departamento_cliente', models.CharField(blank=True, max_length=100)),
                ('productos', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='core.userclientes')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='core.pago')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
