# Generated by Django 5.2.5 on 2025-12-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_pago_cedula_pago_email_pago_nombre_completo_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='pago',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
