# Generated by Django 5.2.5 on 2025-12-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_pago_direccion_pago_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclientes',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
