# Generated by Django 5.2.5 on 2025-12-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_userclientes_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='ancho',
        ),
        migrations.AddField(
            model_name='idea',
            name='categoria',
            field=models.CharField(choices=[('mesas', 'Mesas'), ('sillas', 'Sillas'), ('cajoneras', 'Cajoneras'), ('armarios', 'Armarios'), ('utensilios', 'Utensilios'), ('escritorios', 'Escritorios')], default='mesas', max_length=20),
        ),
        migrations.AddField(
            model_name='idea',
            name='medidas',
            field=models.JSONField(blank=True, help_text='Medidas personalizadas del producto', null=True),
        ),
    ]
