# Generated by Django 5.2.5 on 2025-12-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_idea_altura_remove_idea_ancho_idea_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclientes',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
