# Generated by Django 5.2.5 on 2025-12-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_userclientes_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='veces_editada',
            field=models.IntegerField(default=0, help_text='Número de veces que se ha editado la idea'),
        ),
    ]
