# Generated by Django 5.2.5 on 2025-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0003_alter_empresaregistrada_cedula_representante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaregistrada',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Clave Secreta TOTP'),
        ),
    ]
